### ISSUE TITLE
What was the bug on Steve's slides?

### ISSUE THREAD

**Issue by kgourgou** [UMassAmherst-GRiD/r-workshop-datafest-2015#1]
We should make sure this runs with standard dplyr before sharing.

**Comment by kaloisio** [comment]
People just need to have the latest R version because the joins were built
on the newest version. I'll double check that that was the only issue.

**Comment by salauer** [comment]
Do they need the github version of dplyr too?

**Comment by markwh** [comment]
To do joins? They shouldn't. `right_join` and `full_join` were added in v. 0.4.0 (CRAN has 0.4.1). Others came before that. https://github.com/hadley/dplyr/blob/master/NEWS.md

**Comment by kgourgou** [comment]
Hey @kaloisio, can you take a quick look at that today? :+1:
